import domini.ControladorDomini;
import domini.Llibre;
import domini.Llista;
import domini.Tag;
import herramienta.text.ValidadorLlibre;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistencia.internal.ControladorPersistencia;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * End-to-end tests for backup export + restore.
 *
 * <p>The backup format is a hand-rolled SQL script generated by
 * {@link domini.facade.DelegatCopiaSeguretat#copiaSegToSQL} and consumed by
 * {@link persistencia.dao.LlibreDaoCore#restaurarFromSQL}. These tests
 * round-trip a non-trivial library (books, shelves, tags, joins) through a
 * fresh H2 instance to confirm that every visible relation survives the
 * trip — silent data loss on backup/restore is the worst class of bug for
 * a personal library manager.
 */
class TestExportImportCopiaSeguretatJunit5Test {

    static {
        System.setProperty("biblioteca.test", "true");
        System.setProperty("biblioteca.h2.url",
            "jdbc:h2:mem:backup_roundtrip;MODE=MySQL;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1");
    }

    @BeforeEach
    void reset() {
        ControladorDomini.reinicialitzarForTest();
        ControladorPersistencia.reinicialitzarForTest();
    }

    @AfterEach
    void tearDown() {
        ControladorDomini.reinicialitzarForTest();
        ControladorPersistencia.reinicialitzarForTest();
    }

    @Test
    @DisplayName("copiaSegToSQL: produces a non-empty .sql file with INSERTs and DELETE prelude")
    void copiaSegEscriuSqlAmbInsert() throws Exception {
        ControladorDomini cd = ControladorDomini.getInstance();
        long isbn = 9780306406157L;
        cd.afegirLlibre(ValidadorLlibre.comprovarLlibre(isbn, "Dune", "Herbert", 1965,
            "Sci-fi classic", 10.0, 19.99, true, ""));

        File backup = File.createTempFile("backup_export_", ".sql");
        backup.deleteOnExit();
        cd.copiaSegToSQL(backup);

        assertThat(backup.length()).isGreaterThan(0L);
        String content = Files.readString(backup.toPath(), StandardCharsets.UTF_8);
        assertThat(content).contains("INSERT INTO llibre").contains("9780306406157");
        assertThat(content).contains("DELETE FROM ");
    }

    @Test
    @DisplayName("restaurarFromSQL: empty DB + .sql file → books reload intact")
    void restaurarCarregaLlibres() throws Exception {
        ControladorDomini cd = ControladorDomini.getInstance();
        cd.afegirLlibre(ValidadorLlibre.comprovarLlibre(9780306406157L, "Dune", "Herbert", 1965,
            "Sci-fi classic", 10.0, 19.99, true, ""));

        File backup = File.createTempFile("backup_restore_roundtrip_", ".sql");
        backup.deleteOnExit();
        cd.copiaSegToSQL(backup);

        ControladorDomini.reinicialitzarForTest();
        ControladorPersistencia.reinicialitzarForTest();
        ControladorDomini cd2 = ControladorDomini.getInstance();
        cd2.restaurarFromSQL(backup);

        Llibre back = cd2.obtenirLlibre(9780306406157L);
        assertThat(back.obtenirNom()).isEqualTo("Dune");
        assertThat(back.obtenirAutor()).isEqualTo("Herbert");
        assertThat(back.obtenirAny()).isEqualTo(1965);
        assertThat(back.obtenirValoracio()).isEqualTo(10.0);
        assertThat(back.obtenirPreu()).isEqualTo(19.99);
        assertThat(back.obtenirLlegit()).isTrue();
    }

    @Test
    @DisplayName("roundtrip: backup → reset → restore → books, shelves, tags, joins all survive")
    void roundtripPreservaRelacions() throws Exception {
        long isbn1 = 9780306406157L;
        long isbn2 = 9780132350884L;

        ControladorDomini cd = ControladorDomini.getInstance();
        cd.afegirLlibre(ValidadorLlibre.comprovarLlibre(isbn1, "Dune", "Herbert", 1965, "desc", 9.0, 19.99, true, ""));
        cd.afegirLlibre(ValidadorLlibre.comprovarLlibre(isbn2, "Clean Code", "Martin", 2008, "", 8.0, 29.99, false, ""));
        Llista shelf = cd.afegirLlista("Favorites");
        cd.afegirLlibreToLlista(isbn1, shelf.obtenirId(), 9.0, true);
        Tag tag = cd.afegirTag("sci-fi");
        cd.afegirLlibreToTag(isbn1, tag.obtenirId());

        File backup = File.createTempFile("backup_roundtrip_", ".sql");
        backup.deleteOnExit();
        cd.copiaSegToSQL(backup);

        ControladorDomini.reinicialitzarForTest();
        ControladorPersistencia.reinicialitzarForTest();
        ControladorDomini cd2 = ControladorDomini.getInstance();
        cd2.restaurarFromSQL(backup);

        assertThat(cd2.getSize()).isEqualTo(2);

        Llibre dune = cd2.obtenirLlibre(isbn1);
        assertThat(dune.obtenirNom()).isEqualTo("Dune");
        assertThat(dune.obtenirValoracio()).isEqualTo(9.0);
        assertThat(dune.obtenirLlegit()).isTrue();

        Llibre cc = cd2.obtenirLlibre(isbn2);
        assertThat(cc.obtenirNom()).isEqualTo("Clean Code");
        assertThat(cc.obtenirLlegit()).isFalse();

        assertThat(cd2.obtenirLlistesForLlibre(isbn1)).extracting(Llista::obtenirNom).contains("Favorites");
        assertThat(cd2.obtenirLlistesForLlibre(isbn2)).extracting(Llista::obtenirNom).doesNotContain("Favorites");

        assertThat(cd2.obtenirLlibresWithTag(tag.obtenirId())).containsExactly(isbn1);
    }

    @Test
    @DisplayName("roundtrip: backup file is portable across fresh JVM-style singletons (regression for stale-cache restore)")
    void roundtipResetSingletons() throws Exception {
        ControladorDomini cd = ControladorDomini.getInstance();
        long isbn = 9780306406157L;
        cd.afegirLlibre(ValidadorLlibre.comprovarLlibre(isbn, "Dune", "Herbert", 1965, "", 0.0, 0.0, false, ""));

        File backup = File.createTempFile("backup_reset_", ".sql");
        backup.deleteOnExit();
        cd.copiaSegToSQL(backup);

        ControladorDomini.reinicialitzarForTest();
        ControladorPersistencia.reinicialitzarForTest();

        ControladorDomini cd2 = ControladorDomini.getInstance();
        assertThat(cd2.getSize()).as("reset wiped the library").isZero();

        cd2.restaurarFromSQL(backup);

        assertThat(cd2.getSize()).isEqualTo(1);
        assertThat(cd2.obtenirLlibre(isbn).obtenirNom()).isEqualTo("Dune");
    }
}
