#!/usr/bin/env python3
"""
Reads strings/strings.csv and generates:
  src/web/js/i18n.js
  src/herramienta/I18n.java

CSV format: key,ca,es,en
Lines starting with # are section comments (skipped).
"""

import csv
import sys
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STRINGS_DIR = os.path.join(REPO, "strings")
CSV_PATH  = os.path.join(STRINGS_DIR, "strings.csv")  # legacy monolith (optional)
SPLIT_FILES = ["ui.csv", "errors.csv", "csv.csv"]
JS_PATH   = os.path.join(REPO, "src", "web", "js", "i18n.js")
JAVA_PATH = os.path.join(REPO, "src", "herramienta", "I18n.java")

def read_csv():
    entries = []  # list of (key, ca, es, en)
    sources = [os.path.join(STRINGS_DIR, name) for name in SPLIT_FILES
               if os.path.isfile(os.path.join(STRINGS_DIR, name))]
    if not sources and os.path.isfile(CSV_PATH):
        sources = [CSV_PATH]
    for path in sources:
        with open(path, newline='', encoding='utf-8') as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith('#'):
                    continue
                row = next(csv.reader([stripped]))
                if len(row) < 4 or row[0] == 'key':
                    continue
                entries.append((row[0], row[1], row[2], row[3]))
    return entries

def js_str(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n')

def java_str(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def gen_js(entries):
    def lang_block(lang_idx, entries):
        lines = []
        for key, *vals in entries:
            val = vals[lang_idx] if lang_idx < len(vals) else vals[0]
            lines.append(f"        {key}: '{js_str(val)}',")
        return '\n'.join(lines)

    ca_block = lang_block(0, entries)
    es_block = lang_block(1, entries)
    en_block = lang_block(2, entries)

    return f"""// AUTO-GENERATED by scripts/gen_strings.py — edit strings/strings.csv instead
const LANGS = {{
    ca: {{
{ca_block}
    }},
    es: {{
{es_block}
    }},
    en: {{
{en_block}
    }},
}};

window.lang = localStorage.getItem('biblioteca_lang') || 'ca';

function t(key, ...args) {{
    let str = (LANGS[window.lang] || LANGS.ca)[key] || LANGS.ca[key] || key;
    args.forEach((a, i) => {{ str = str.replace('{{' + i + '}}', a); }});
    return str;
}}

function applyI18n() {{
    document.querySelectorAll('[data-i18n]').forEach(el => {{
        el.textContent = t(el.getAttribute('data-i18n'));
    }});
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {{
        el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
    }});
    document.querySelectorAll('[data-i18n-title]').forEach(el => {{
        el.title = t(el.getAttribute('data-i18n-title'));
    }});
    const sel = document.getElementById('lang-select');
    if (sel) sel.value = window.lang;
}}

document.addEventListener('DOMContentLoaded', () => {{
    applyI18n();
    const sel = document.getElementById('lang-select');
    if (sel) {{
        sel.value = window.lang;
        sel.addEventListener('change', () => {{
            localStorage.setItem('biblioteca_lang', sel.value);
            location.reload();
        }});
    }}
}});
"""

def gen_java(entries):
    rows = []
    for key, ca, es, en in entries:
        rows.append(f'        T("{java_str(key)}", "{java_str(ca)}", "{java_str(es)}", "{java_str(en)}");')
    table_lines = '\n'.join(rows)

    return f"""// AUTO-GENERATED by scripts/gen_strings.py — edit strings/strings.csv instead
package herramienta;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.UIManager;

public class I18n {{

    // index: 0=ca  1=es  2=en
    private static final Map<String, String[]> TABLE = new LinkedHashMap<>();

    static {{
{table_lines}
    }}

    private static void T(String key, String ca, String es, String en) {{
        TABLE.put(key, new String[]{{ca, es, en}});
    }}

    public static String t(String key, Object... args) {{
        String[] vals = TABLE.get(key);
        String raw;
        if (vals == null) {{
            String msg = "[I18n] Missing key: " + key;
            System.err.println(msg);
            if ("true".equals(System.getProperty("biblioteca.test")))
                throw new IllegalStateException(msg);
            raw = key;
        }} else {{
            int idx = langIndex();
            raw = vals[Math.min(idx, vals.length - 1)];
        }}
        if (args.length > 0 && !raw.contains("{{0}}")) {{
            System.err.println("[I18n] Key '" + key + "' has no placeholder for args");
        }}
        for (int i = 0; i < args.length; i++)
            raw = raw.replace("{{" + i + "}}", String.valueOf(args[i]));
        return raw;
    }}

    /** Localize JOptionPane button labels after a language change. */
    public static void applySwingOptionPane() {{
        UIManager.put("OptionPane.okButtonText",     t("btn_ok"));
        UIManager.put("OptionPane.cancelButtonText", t("btn_cancel"));
        UIManager.put("OptionPane.yesButtonText",  t("btn_yes"));
        UIManager.put("OptionPane.noButtonText",   t("btn_no"));
    }}

    private static int langIndex() {{
        String lang = Config.getLang();
        if ("es".equals(lang)) return 1;
        if ("en".equals(lang)) return 2;
        return 0; // ca default
    }}
}}
"""

def main():
    entries = read_csv()
    print(f"Read {len(entries)} string entries from {CSV_PATH}")

    js = gen_js(entries)
    with open(JS_PATH, 'w', encoding='utf-8') as f:
        f.write(js)
    print(f"Written: {JS_PATH}")

    java = gen_java(entries)
    with open(JAVA_PATH, 'w', encoding='utf-8') as f:
        f.write(java)
    print(f"Written: {JAVA_PATH}")

if __name__ == '__main__':
    main()
