#!/usr/bin/env python3
"""
Llegeix strings/*.csv i genera:
  src/herramienta/I18n.java
  src/herramienta/strings_ca.properties
  src/herramienta/strings_es.properties
  src/herramienta/strings_en.properties

Format CSV: key,ca,es,en
Les línies que comencen amb # són comentaris de secció (s'ignoren).
"""

import csv
import sys
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STRINGS_DIR = os.path.join(REPO, "strings")
CSV_PATH  = os.path.join(STRINGS_DIR, "strings.csv")  # legacy monolith (optional)
SPLIT_FILES = ["ui.csv", "errors.csv", "csv.csv"]
JAVA_PATH = os.path.join(REPO, "src", "herramienta", "I18n.java")
PROP_PATHS = {
    "ca": os.path.join(REPO, "src", "herramienta", "strings_ca.properties"),
    "es": os.path.join(REPO, "src", "herramienta", "strings_es.properties"),
    "en": os.path.join(REPO, "src", "herramienta", "strings_en.properties"),
}

def read_csv():
    entries = []  # list of (key, ca, es, en)
    sources = [os.path.join(STRINGS_DIR, name) for name in SPLIT_FILES
               if os.path.isfile(os.path.join(STRINGS_DIR, name))]
    if not sources and os.path.isfile(CSV_PATH):
        sources = [CSV_PATH]
    for path in sources:
        with open(path, newline='', encoding='utf-8') as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith('#'):
                    continue
                row = next(csv.reader([stripped]))
                if len(row) < 4 or row[0] == 'key':
                    continue
                entries.append((row[0], row[1], row[2], row[3]))
    return entries

def java_str(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def java_prop_str(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def gen_java(entries):
    rows = []
    for key, ca, es, en in entries:
        rows.append(f'        T("{java_str(key)}", "{java_str(ca)}", "{java_str(es)}", "{java_str(en)}");')
    table_lines = '\n'.join(rows)

    return f"""// AUTO-GENERATED by scripts/gen_strings.py — edit strings/strings.csv instead
package herramienta;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.UIManager;

public class I18n {{

    // index: 0=ca  1=es  2=en
    private static final Map<String, String[]> TABLE = new LinkedHashMap<>();

    static {{
{table_lines}
    }}

    private static void T(String key, String ca, String es, String en) {{
        TABLE.put(key, new String[]{{ca, es, en}});
    }}

    public static String t(String key, Object... args) {{
        String[] vals = TABLE.get(key);
        String raw;
        if (vals == null) {{
            String msg = "[I18n] Missing key: " + key;
            System.err.println(msg);
            if ("true".equals(System.getProperty("biblioteca.test")))
                throw new IllegalStateException(msg);
            raw = key;
        }} else {{
            int idx = langIndex();
            raw = vals[Math.min(idx, vals.length - 1)];
        }}
        if (args.length > 0 && !raw.contains("{{0}}")) {{
            System.err.println("[I18n] Key '" + key + "' has no placeholder for args");
        }}
        for (int i = 0; i < args.length; i++)
            raw = raw.replace("{{" + i + "}}", String.valueOf(args[i]));
        return raw;
    }}

    /** Localize JOptionPane button labels after a language change. */
    public static void applySwingOptionPane() {{
        UIManager.put("OptionPane.okButtonText",     t("btn_ok"));
        UIManager.put("OptionPane.cancelButtonText", t("btn_cancel"));
        UIManager.put("OptionPane.yesButtonText",  t("btn_yes"));
        UIManager.put("OptionPane.noButtonText",   t("btn_no"));
    }}

    private static int langIndex() {{
        String lang = Config.getLang();
        if ("es".equals(lang)) return 1;
        if ("en".equals(lang)) return 2;
        return 0; // ca default
    }}
}}
"""

def gen_props(entries, lang_idx):
    lines = []
    for key, *vals in entries:
        val = vals[lang_idx] if lang_idx < len(vals) else vals[0]
        lines.append(f"{java_str(key)}={java_prop_str(val)}")
    return '\n'.join(lines)

def main():
    entries = read_csv()
    print(f"S'han llegit {len(entries)} entrades de cadenes")

    java = gen_java(entries)
    with open(JAVA_PATH, 'w', encoding='utf-8') as f:
        f.write(java)
    print(f"Escrit: {JAVA_PATH}")

    for lang_code, path in PROP_PATHS.items():
        lang_idx = {"ca": 0, "es": 1, "en": 2}[lang_code]
        props = gen_props(entries, lang_idx)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(props)
        print(f"Escrit: {path}")

if __name__ == '__main__':
    main()
