// AUTO-GENERATED by scripts/gen_strings.py — edit strings/strings.csv instead
package herramienta;

import java.util.ResourceBundle;
import javax.swing.UIManager;

public class I18n {

    private static ResourceBundle bundle(Lang lang) {
        String base = "strings_" + lang.code();
        return ResourceBundle.getBundle(base, java.util.Locale.ROOT);
    }

    private static Lang currentLang() {
        return Lang.fromCode(Config.getLang());
    }

    public static String t(String key, Object... args) {
        Lang lang = currentLang();
        String raw;
        try {
            raw = bundle(lang).getString(key);
        } catch (java.util.MissingResourceException e) {
            String msg = "[I18n] Missing key: " + key;
            System.err.println(msg);
            if ("true".equals(System.getProperty("biblioteca.test")))
                throw new IllegalStateException(msg);
            raw = key;
        }
        if (args.length > 0 && !raw.contains("{0}")) {
            System.err.println("[I18n] Key '" + key + "' has no placeholder for args");
        }
        for (int i = 0; i < args.length; i++)
            raw = raw.replace("{" + i + "}", String.valueOf(args[i]));
        return raw;
    }

    /** Localize JOptionPane button labels after a language change. */
    public static void applySwingOptionPane() {
        UIManager.put("OptionPane.okButtonText",     t("btn_ok"));
        UIManager.put("OptionPane.cancelButtonText", t("btn_cancel"));
        UIManager.put("OptionPane.yesButtonText",  t("btn_yes"));
        UIManager.put("OptionPane.noButtonText",   t("btn_no"));
    }
}